### ISSUE TITLE
Lots of references to expected<E,T>

### ISSUE THREAD

**Issue by TBBle** [ptal/std-expected-proposal#24]
Looking at [the last generated PDF](http://www.hyc.io/boost/expected-proposal.pdf) there's still lots of places that use `expected<E,T>` instead of `expected<T,E>`.

Most of them show up when searching for `expected<e` or `expected<decay_t<e` (case insensitively), but there might be others lurking. That'll pick up `E`, `exception_ptr` and `error_condition` at least.

**Comment by viboes** [comment]
I have moved to markdown format in https://github.com/viboes/std-make/blob/master/doc/proposal/expected/DXXXXR0_expected.md

**Comment by TBBle** [comment]
Only one left I can see, `expected<error_condition, int> safe_divide(int i, int j)`.

**Comment by viboes** [comment]
Thanks. fixed in new repo with MarkDown format. Please move to the other repository.

**Comment by TBBle** [comment]
@viboes Just to be clear, you want issue reports on the new repository only?

**Comment by viboes** [comment]
Yes. I have moved to this other repository.
