### ISSUE TITLE
make_expected cannot produce expected<T,E!=exception_ptr>

### ISSUE THREAD

**Issue by TBBle** [ptal/std-expected-proposal#25]
There's three signatures for make_expected:
```c++
template <class T> constexpr expected<decay_t<T>> make_expected(T&& v);
expected<void> make_expected();
template <class E> expected<void, E> make_expected();
```

Which means I can do:

```c++
expected<int, exception_ptr> d = make_expected(5);
expected<void, exception_ptr> c = make_expected();
expected<void, error_condition> b = make_expected<error_condition>();
```

but there's no way I can see to do
```c++
expected<int, error_condition> a = make_expected<error_condition>(5);
```

**Comment by viboes** [comment]
Yes. I don't know how to do it.

**Comment by rodiers** [comment]
template <class T, class E>> constexpr expected<decay_t<T>, E> make_expected(T&& v);

**Comment by TBBle** [comment]
Won't that require this:
```c++
expected<int, error_condition> = make_expected<int, error_condition>(5);
```

That seems good enough to me, particularly when dealing with integral types, but it is more verbose than the other cases.

**Comment by viboes** [comment]
`expected<int, error_condition>(5)`?

**Comment by TBBle** [comment]
Yeah, pretty-much. I can't see any use-case for that form of make_expected off-hand.

**Comment by TBBle** [comment]
Would it make sense for a non-error expected<T,A> to be assignable to expected<T,B>?
Then
```c++
expected<int, error_condition> = make_expected( 5 );
```
would do what I wanted, but maybe opens up a lot of other -daft- unexpected behaviour.

Alternatively, why isn't this as simple as
```c++
template< typename E, typename T >
expected< typename std::decay<T>::type, E > make_expected( T&& v );

expected<int, error_condition> a = make_expected<error_condition>( 5 );
```

It does make the syntax odd if you try to be explicit:
```c++
auto a = make_expected<error_condition, uint32_t>( 5 );
// versus
expected<uint32_t, error_condition> a( 5 );
```

But that opens the question, was _is_ the expected use-case for `make_expected`? I understood that the usual use-case for `expected` is 'return types', or perhaps being assigned to.

**Comment by viboes** [comment]
You have almost found the solution. 

Adding this overload 

```c++
template< typename E, typename T >
expected< typename std::decay<T>::type, E > make_expected( T&& v );
```
you can do

```
auto a = make_expected<error_condition>( 5 );
```

But now 

```c++
expected<short> a = make_expected<short>( 5 );
```

fails as it takes the short a error

```
error: no viable conversion from 'expected<decay_t<int>, short>' to 'expected<short, (default) std::exception_ptr>'
  expected<short> e = make_expected<short>( 5 );
```
but I WANT it to use the overload and accept conversions to `short`

```
template <typename T>
expected<decay_t<T>, std::exception_ptr> make_expected(T&& v)
```
Note that 
```c++
auto a = make_expected<short>( 5 );
```
compile, but `a` has type `expected<int, short>` :(

Is this a bad expectation?

**Comment by TBBle** [comment]
I'm starting to feel that `make_expected` isn't a terrific API at all. The question of "What do I expect from `make_expected( 5 )` or `make_expected( error_condition )` is easy to answer for a human, but not really feasible for a template writer.

Motivating counter-examples:

```c++
expected<string, string> statusOrExcuse1 = make_expected("Busy"s);
expected<string, string> statusOrExcuse2 = make_expected<string>("Busy"s);
```

It's issues like this that motivated `unexpected_type` in the first place, right?

The following seems reasonably usable, but there's still not a lot of clarity in providing one template parameter to a `make_` function, which is unrelated to the function parameter, particularly when they're the same type. It smells of "Easy to get wrong" to me.

```c++
// All expected<string, string>
auto status1 = make_expected</*E=*/string>("Busy"s);
auto excuse1 = make_expected</*T=*/string>(make_unexpected("Busy"s));
auto excuse2 = make_expected</*T=*/string>(unexpect, "Busy"s);
```

**Comment by viboes** [comment]
The last two are not supported.

**Comment by TBBle** [comment]
My point was that
```c++
auto status1 = make_expected<string>("Busy"s);
auto excuse1 = make_expected_from_error<string>("Busy"s));
```
is completely non-obvious that the template parameter is unrelated to the type of the function parameter.

I don't use the `make_*` idiom a lot yet, but my feeling is that if you have to give it explicit template parameters, (and they're not clearly something like a policy template) it might not be the right idiom to use.

**Comment by viboes** [comment]
You have 

```c++
auto p = make_shared<string>("Busy");
```

What is obvious for some is not for others. We need to understand the rules.

Any suggestion is welcome.

**Comment by TBBle** [comment]
That's actually my point. In
```c++
auto p = make_shared<string>("Busy");
```
the `string` is actually related to `"Busy"`, as an optional coercion point. And so you get compilation failures if you try to do things that don't  support coercion such as:
```c++
auto p = make_shared<string>(7);
```

For `make_expected` and similar routines, we must have a template parameter, and then deduce the _other_ parameter we need from the provided value.

My feeling is that `make_execpected<T>` should produce `expected<T>`, (like `make_shared`, `make_unique`, `make_pair`, etc.) but here it's `expected<SomethingElse,T>`.

**Comment by viboes** [comment]
`make_expected<string>("Busy")` result type is `expected<string>` and not `expected<SomethingElse,string>`.

**Comment by TBBle** [comment]
Right. I skipped a track mentally there. The issue then is that

```c++
make_expected<string>();
```
is `expected<void, string>`. So we have two overloads of `make_expected` with one template parameter, that do wildly different and unrelated things. By the other given patterns, that should have been `expected<string>( string() );`.

For consistency, what I'd expect to see is:
* `make_expected(T&& value) => expected<decay_t<T>>(value)`
* `make_expected<T>(U&& value) => expected<T>(value)`
* * `make_expected<T>() => expected<T>()`
* `make_expected<T,E>(U&& value) => expected<T,E>(value)`
* * `make_expected<T,E>() => expected<T,E>()`

And specialising for `void`
* `make_expected() => expected<void>()`

Similarly
* `make_expected_from_error<T>(E&& err) => expected<T,decay_t<E>>(make_unexpected(err))`
* `make_expected_from_error<T,E>(U&& err) => expected<T,E>(make_unexpected(err))`

In the local use-case that brought me in the first place, we're aliasing expected to have a different default E, because we don't actually need to carry exception_ptr, we're in a non-exception environment so we're carrying an error_condition instead. However, we've also found that outside the unit-tests of expected itself, we haven't needed to use make_expected very much, as it's usually a return value type, and we're relying on the assignment operators from unexpected_type or value_type.

**Comment by viboes** [comment]
I recognize that the following is disturbing

```
auto e = make_expected<string>(); // decltype(e) is expected<void, string>
```
I could remove this overload.

However, I don't see any added value to, as the RHS is shorter

```
* make_expected<T>(U&& value) => expected<T>(value)
* make_expected<T>() => expected<T>()
* make_expected<T,E>(U&& value) => expected<T,E>(value)
* make_expected<T,E>() => expected<T,E>() 
```

When do you need those `make_expected` overloads that can not be replaced by the RHS?

**Comment by viboes** [comment]
I believe that we could add

```
make_expected_from_error<T,E>(U&& err) => expected<T,E>(make_unexpected(err))
```

**Comment by viboes** [comment]
Please take a look at the following commits

https://github.com/ptal/expected/commit/1b55372189235692ee017a1cfdce63b703ae7119

https://github.com/ptal/expected/commit/2d1babd853eb845e309da83f3f8d5b538df5fb10

**Comment by TBBle** [comment]
Agreed, those changes look reasonable to me. `make_expected` looks consistent now, and doesn't seem to hold any surprises.

**Comment by viboes** [comment]
Thanks for all.
