### ISSUE TITLE
unexpected<E> or unexpected_type<E>

### ISSUE THREAD

**Issue by TBBle** [ptal/std-expected-proposal#26]
Both `unexpected<E>` and `unexpected_type<E>` appear in the text. The former is mostly associated with `operator==` and `get_unexpected`, and is also used in the discussion of Variant in Appendix III.

*[unexpected.factories]* conflates the two, so I assume that a rename from one to the other was only partially completed.

I'd lean towards `expected_type` because otherwise it feels ambiguous with the use of "expected" in *[expected.defs]*

And while I'm looking at it, the *Relational operators* section also marks unexpected as code a couple of times, when it's using the non-code meaning of "expected containing an E".

**Comment by viboes** [comment]
Thanks for catching this. fixed any use of unexpected<E> in new repo with MarkDown format.
